In [1]:
print("Hello World :)")

Hello World :)


## Numpy basics

In [2]:
import numpy as np

In [3]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [5]:
np.arange(10, 50, 2.5, dtype=float)

array([10. , 12.5, 15. , 17.5, 20. , 22.5, 25. , 27.5, 30. , 32.5, 35. ,
       37.5, 40. , 42.5, 45. , 47.5])

In [6]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
# reshape to create new
arr_new = arr.reshape(3, 2, 4)
arr_new

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
# reshape the same array
arr.shape = (3, 2, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
arr = np.arange(20)
print("%r" % arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])


In [11]:
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [12]:
# Boolean index
arr[arr%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
# row, col
arr[1, 2]

7

In [15]:
arr[[1,2]]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
# fetch the third column
arr[:, 2]

array([ 2,  7, 12, 17])

In [17]:
# from 2 and 3rd row, take 2 and 3rd column
arr[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

In [18]:
arr[0:3:2, 1:4:2]

array([[ 1,  3],
       [11, 13]])

In [19]:
b = arr > 8
b

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [20]:
arr[b[:, 4], 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [21]:
# broadcasting is resizing one of the array to that arithmatic operation can be performed 
print("%r \n+" % arr)
print("%r" % np.arange(5))
arr + np.arange(5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]) 
+
array([0, 1, 2, 3, 4])


array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23]])

In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [24]:
x[:, np.newaxis] + x[np.newaxis, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [25]:
# broadcasting may not always work
arr + np.arange(4)

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [ ]:
# Supports lin alg problems
np.linalg.eig(np.array([[1, -1], [1, 1]]))


In [ ]:
np.random.binomial(100, 0.1)